language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t johntam/docker-react .

script:
  - docker run -e CI=true johntam/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-266225444611"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
